GB-14 smoking detection demo
videogorillas/videogorillas.github.io pull request #17
Opened 2018-05-03 13:52 UTC by mytcat

![screen shot 2018-05-03 at 4 51 26 pm](https://user-images.githubusercontent.com/1709593/39580689-5f7e3760-4ef2-11e8-9f59-ba83decedb74.png)

2018-05-03 16:08 UTC, A-Bush requested changes

2018-05-03 16:08 UTC, A-Bush commented on index.html
> +					<h1>STANDARTS & PRACTICES</h1>
`&` -> `&amp;`

2018-05-03 16:08 UTC, A-Bush commented on index.html
> +        if(/iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream) {
do we handle Safari users or not?

2018-05-03 16:08 UTC, A-Bush commented on index.html
> +		    <section class="page7 section-no-border">
is it safe to delete id?

2018-05-03 16:08 UTC, A-Bush commented on index.html
> +    <script>
why script included in html and is not separate .js file?

2018-05-03 16:08 UTC, A-Bush commented on index.html
> +                let ocr = TimecodeOCRPlugin.init(elements.player.player, "newocr.tf/model.json");
does OCR works on video without timecodes?

2018-05-04 12:15 UTC, mytcat commented on index.html
> +		    <section class="page7 section-no-border">
Yes. I have checked it before deleting.

2018-05-04 12:15 UTC, mytcat commented on index.html
> +        if(/iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream) {
We don't need to handle Safari. Just checking users who use Apple mobile devices.

2018-05-04 13:51 UTC, A-Bush approved these changes

2018-05-04 13:51 UTC, merged